const menuData = [
    {
        id: 1,
        order: 1,
        name: 'Dashboard',
        icon: 'ti ti-home',
        url: '/dashboard',
        status: 'Active',
    },
    {
        id: 2,
        order: 2,
        name: 'Notary Dashboard',
        icon: 'ti ti-home',
        url: '-',
        status: 'Active',
    },
    {
        id: 3,
        order: 3,
        name: 'Job Management',
        icon: 'ti ti-files',
        url: '-',
        status: 'Active',
    },
    {
        id: 4,
        order: 4,
        name: 'Title Management',
        icon: 'ti ti-building',
        url: '/title-company',
        status: 'Active',
    },
    {
        id: 5,
        order: 5,
        name: 'Notary Management',
        icon: 'ti ti-certificate',
        url: '/notary-management',
        status: 'Active',
    },
    {
        id: 6,
        order: 6,
        name: 'User Management',
        icon: 'ti ti-users',
        url: '/user-management',
        status: 'Active',
    },
    {
        id: 7,
        order: 7,
        name: 'Services',
        icon: 'ti ti-settings',
        url: '/services',
        status: 'Active',
    },
    {
        id: 8,
        order: 8,
        name: 'Client Management',
        icon: 'ti ti-edit',
        url: '/client-management',
        status: 'Active',
    },
    {
        id: 9,
        order: 9,
        name: 'Menu Management',
        icon: 'ti ti-category',
        url: '/menu-management',
        status: 'Active',
    },
    {
        id: 10,
        order: 10,
        name: 'Notarization Logs',
        icon: 'ti ti-book',
        url: '/notarization-logs',
        status: 'Active',
    },
]

export default menuData;