const notaryInfo = [
    {
        id: 'ANDPET01',
        fullName: 'Peta-Gaye Anderson',
        email: 'petagaye@pglservices.net',
        city: 'sunrise',
        certified: true,
        status: 'Enabled',
    },
    {
        id: 'ARNPAT08',
        fullName: 'Patricia Arnaiz Chipoco',
        email: 'patricia.arnaiz1@gmail.com',
        city: 'Palm Bay',
        certified: false,
        status: 'Disabled',
    },
    {
        id: 'FEADAL05',
        fullName: 'Dalarrion featherston',
        email: 'dalarrionf@gmail.com',
        city: 'hampton',
        certified: true,
        status: 'Enabled',
    },
    {
        id: 'KARSUS07',
        fullName: 'Susan Karen Oliveira',
        email: 'susan@oliveriamobilenotary.com',
        city: 'Palm Bay',
        certified: false,
        status: 'Disabled',
    },
    {
        id: 'LEHBRI10',
        fullName: 'Brian Lehman',
        email: 'brianlehman97@gmail.com',
        city: '..',
        certified: true,
        status: 'Enabled',
    },
    {
        id: 'MCCVAN04',
        fullName: 'Vanessa McCarsky',
        email: 'enotaryrva@gmail.com',
        city: 'Henrico',
        certified: true,
        status: 'Enabled',
    },
    {
        id: 'N-1-a5d25',
        fullName: 'Muhammad Umer',
        email: 'm.umer@softvira.com',
        city: 'Ashland',
        certified: false,
        status: 'Disabled',
    },
]

export default notaryInfo;